version: '3.8'

services:
  dashboard-hercules:
    build: .
    container_name: dashboard-hercules
    restart: always
    ports:
      - "8082:80"
    environment:
      - NODE_ENV=production
    networks:
      - default
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hercules.rule=Host(`app.hercules.atveza.com`)"
      - "traefik.http.routers.hercules.entrypoints=websecure"
      - "traefik.http.routers.hercules.tls.certresolver=mytlschallenge"
      - "traefik.http.services.hercules.loadbalancer.server.port=80"
      - "traefik.docker.network=root_default"

  backend:
    build: ./server
    container_name: dashboard-hercules-backend
    restart: always
    volumes:
      - ./server/prisma:/app/prisma
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=hercules-secret-key-change-me
      - DATABASE_URL=file:./dev.db
    networks:
      - default

networks:
  root_default:
    external: true
